<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('countries')->truncate();

        $countries = [
            ['code' => 'AF', 'name' => 'Afghanistan', 'phone_code' => '+93', 'timezone' => 'Asia/Kabul'],
            ['code' => 'AL', 'name' => 'Albania', 'phone_code' => '+355', 'timezone' => 'Europe/Tirane'],
            ['code' => 'DZ', 'name' => 'Algeria', 'phone_code' => '+213', 'timezone' => 'Africa/Algiers'],
            ['code' => 'AS', 'name' => 'American Samoa', 'phone_code' => '+1-684', 'timezone' => 'Pacific/Pago_Pago'],
            ['code' => 'AD', 'name' => 'Andorra', 'phone_code' => '+376', 'timezone' => 'Europe/Andorra'],
            ['code' => 'AO', 'name' => 'Angola', 'phone_code' => '+244', 'timezone' => 'Africa/Luanda'],
            ['code' => 'AI', 'name' => 'Anguilla', 'phone_code' => '+1-264', 'timezone' => 'America/Anguilla'],
            ['code' => 'AQ', 'name' => 'Antarctica', 'phone_code' => '+672', 'timezone' => 'Antarctica/McMurdo'],
            ['code' => 'AG', 'name' => 'Antigua and Barbuda', 'phone_code' => '+1-268', 'timezone' => 'America/Antigua'],
            ['code' => 'AR', 'name' => 'Argentina', 'phone_code' => '+54', 'timezone' => 'America/Argentina/Buenos_Aires'],
            ['code' => 'AM', 'name' => 'Armenia', 'phone_code' => '+374', 'timezone' => 'Asia/Yerevan'],
            ['code' => 'AW', 'name' => 'Aruba', 'phone_code' => '+297', 'timezone' => 'America/Aruba'],
            ['code' => 'AU', 'name' => 'Australia', 'phone_code' => '+61', 'timezone' => 'Australia/Sydney'],
            ['code' => 'AT', 'name' => 'Austria', 'phone_code' => '+43', 'timezone' => 'Europe/Vienna'],
            ['code' => 'AZ', 'name' => 'Azerbaijan', 'phone_code' => '+994', 'timezone' => 'Asia/Baku'],
            ['code' => 'BS', 'name' => 'Bahamas', 'phone_code' => '+1-242', 'timezone' => 'America/Nassau'],
            ['code' => 'BH', 'name' => 'Bahrain', 'phone_code' => '+973', 'timezone' => 'Asia/Bahrain'],
            ['code' => 'BD', 'name' => 'Bangladesh', 'phone_code' => '+880', 'timezone' => 'Asia/Dhaka'],
            ['code' => 'BB', 'name' => 'Barbados', 'phone_code' => '+1-246', 'timezone' => 'America/Barbados'],
            ['code' => 'BY', 'name' => 'Belarus', 'phone_code' => '+375', 'timezone' => 'Europe/Minsk'],
            ['code' => 'BE', 'name' => 'Belgium', 'phone_code' => '+32', 'timezone' => 'Europe/Brussels'],
            ['code' => 'BZ', 'name' => 'Belize', 'phone_code' => '+501', 'timezone' => 'America/Belize'],
            ['code' => 'BJ', 'name' => 'Benin', 'phone_code' => '+229', 'timezone' => 'Africa/Porto-Novo'],
            ['code' => 'BM', 'name' => 'Bermuda', 'phone_code' => '+1-441', 'timezone' => 'Atlantic/Bermuda'],
            ['code' => 'BT', 'name' => 'Bhutan', 'phone_code' => '+975', 'timezone' => 'Asia/Thimphu'],
            ['code' => 'BO', 'name' => 'Bolivia', 'phone_code' => '+591', 'timezone' => 'America/La_Paz'],
            ['code' => 'BA', 'name' => 'Bosnia & Herzegovina', 'phone_code' => '+387', 'timezone' => 'Europe/Sarajevo'],
            ['code' => 'BW', 'name' => 'Botswana', 'phone_code' => '+267', 'timezone' => 'Africa/Gaborone'],
            ['code' => 'BR', 'name' => 'Brazil', 'phone_code' => '+55', 'timezone' => 'America/Sao_Paulo'],
            ['code' => 'IO', 'name' => 'British Indian Ocean Territory', 'phone_code' => '+246', 'timezone' => 'Indian/Chagos'],
            ['code' => 'BN', 'name' => 'Brunei Darussalam', 'phone_code' => '+673', 'timezone' => 'Asia/Brunei'],
            ['code' => 'BG', 'name' => 'Bulgaria', 'phone_code' => '+359', 'timezone' => 'Europe/Sofia'],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'phone_code' => '+226', 'timezone' => 'Africa/Ouagadougou'],
            ['code' => 'BI', 'name' => 'Burundi', 'phone_code' => '+257', 'timezone' => 'Africa/Bujumbura'],
            ['code' => 'KH', 'name' => 'Cambodia', 'phone_code' => '+855', 'timezone' => 'Asia/Phnom_Penh'],
            ['code' => 'CM', 'name' => 'Cameroon', 'phone_code' => '+237', 'timezone' => 'Africa/Douala'],
            ['code' => 'CA', 'name' => 'Canada', 'phone_code' => '+1', 'timezone' => 'America/Toronto'],
            ['code' => 'CV', 'name' => 'Cape Verde', 'phone_code' => '+238', 'timezone' => 'Atlantic/Cape_Verde'],
            ['code' => 'KY', 'name' => 'Cayman Islands', 'phone_code' => '+1-345', 'timezone' => 'America/Cayman'],
            ['code' => 'CF', 'name' => 'Central African Republic', 'phone_code' => '+236', 'timezone' => 'Africa/Bangui'],
            ['code' => 'TD', 'name' => 'Chad', 'phone_code' => '+235', 'timezone' => 'Africa/Ndjamena'],
            ['code' => 'CL', 'name' => 'Chile', 'phone_code' => '+56', 'timezone' => 'America/Santiago'],
            ['code' => 'CN', 'name' => 'China', 'phone_code' => '+86', 'timezone' => 'Asia/Shanghai'],
            ['code' => 'CX', 'name' => 'Christmas Island', 'phone_code' => '+61', 'timezone' => 'Indian/Christmas'],
            ['code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'phone_code' => '+61', 'timezone' => 'Indian/Cocos'],
            ['code' => 'CO', 'name' => 'Colombia', 'phone_code' => '+57', 'timezone' => 'America/Bogota'],
            ['code' => 'KM', 'name' => 'Comoros', 'phone_code' => '+269', 'timezone' => 'Indian/Comoro'],
            ['code' => 'CG', 'name' => 'Congo (Brazzaville)', 'phone_code' => '+242', 'timezone' => 'Africa/Brazzaville'],
            ['code' => 'CD', 'name' => 'Congo, Democratic Republic (Kinshasa)', 'phone_code' => '+243', 'timezone' => 'Africa/Kinshasa'],
            ['code' => 'CK', 'name' => 'Cook Islands', 'phone_code' => '+682', 'timezone' => 'Pacific/Rarotonga'],
            ['code' => 'CR', 'name' => 'Costa Rica', 'phone_code' => '+506', 'timezone' => 'America/Costa_Rica'],
            ['code' => 'HR', 'name' => 'Croatia', 'phone_code' => '+385', 'timezone' => 'Europe/Zagreb'],
            ['code' => 'CU', 'name' => 'Cuba', 'phone_code' => '+53', 'timezone' => 'America/Havana'],
            ['code' => 'CY', 'name' => 'Cyprus', 'phone_code' => '+357', 'timezone' => 'Asia/Nicosia'],
            ['code' => 'CZ', 'name' => 'Czech Republic', 'phone_code' => '+420', 'timezone' => 'Europe/Prague'],
            ['code' => 'DK', 'name' => 'Denmark', 'phone_code' => '+45', 'timezone' => 'Europe/Copenhagen'],
            ['code' => 'DJ', 'name' => 'Djibouti', 'phone_code' => '+253', 'timezone' => 'Africa/Djibouti'],
            ['code' => 'DM', 'name' => 'Dominica', 'phone_code' => '+1-767', 'timezone' => 'America/Dominica'],
            ['code' => 'DO', 'name' => 'Dominican Republic', 'phone_code' => '+1-809', 'timezone' => 'America/Santo_Domingo'],
            ['code' => 'EC', 'name' => 'Ecuador', 'phone_code' => '+593', 'timezone' => 'America/Guayaquil'],
            ['code' => 'EG', 'name' => 'Egypt', 'phone_code' => '+20', 'timezone' => 'Africa/Cairo'],
            ['code' => 'SV', 'name' => 'El Salvador', 'phone_code' => '+503', 'timezone' => 'America/El_Salvador'],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'phone_code' => '+240', 'timezone' => 'Africa/Malabo'],
            ['code' => 'ER', 'name' => 'Eritrea', 'phone_code' => '+291', 'timezone' => 'Africa/Asmara'],
            ['code' => 'EE', 'name' => 'Estonia', 'phone_code' => '+372', 'timezone' => 'Europe/Tallinn'],
            ['code' => 'ET', 'name' => 'Ethiopia', 'phone_code' => '+251', 'timezone' => 'Africa/Addis_Ababa'],
            ['code' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'phone_code' => '+500', 'timezone' => 'Atlantic/Stanley'],
            ['code' => 'FO', 'name' => 'Faroe Islands', 'phone_code' => '+298', 'timezone' => 'Atlantic/Faroe'],
            ['code' => 'FJ', 'name' => 'Fiji', 'phone_code' => '+679', 'timezone' => 'Pacific/Fiji'],
            ['code' => 'FI', 'name' => 'Finland', 'phone_code' => '+358', 'timezone' => 'Europe/Helsinki'],
            ['code' => 'FR', 'name' => 'France', 'phone_code' => '+33', 'timezone' => 'Europe/Paris'],
            ['code' => 'GF', 'name' => 'French Guiana', 'phone_code' => '+594', 'timezone' => 'America/Cayenne'],
            ['code' => 'PF', 'name' => 'French Polynesia', 'phone_code' => '+689', 'timezone' => 'Pacific/Tahiti'],
            ['code' => 'TF', 'name' => 'French Southern Territories', 'phone_code' => '+262', 'timezone' => 'Indian/Kerguelen'],
            ['code' => 'GA', 'name' => 'Gabon', 'phone_code' => '+241', 'timezone' => 'Africa/Libreville'],
            ['code' => 'GM', 'name' => 'Gambia', 'phone_code' => '+220', 'timezone' => 'Africa/Banjul'],
            ['code' => 'GE', 'name' => 'Georgia', 'phone_code' => '+995', 'timezone' => 'Asia/Tbilisi'],
            ['code' => 'DE', 'name' => 'Germany', 'phone_code' => '+49', 'timezone' => 'Europe/Berlin'],
            ['code' => 'GH', 'name' => 'Ghana', 'phone_code' => '+233', 'timezone' => 'Africa/Accra'],
            ['code' => 'GI', 'name' => 'Gibraltar', 'phone_code' => '+350', 'timezone' => 'Europe/Gibraltar'],
            ['code' => 'GR', 'name' => 'Greece', 'phone_code' => '+30', 'timezone' => 'Europe/Athens'],
            ['code' => 'GL', 'name' => 'Greenland', 'phone_code' => '+299', 'timezone' => 'America/Godthab'],
            ['code' => 'GD', 'name' => 'Grenada', 'phone_code' => '+1-473', 'timezone' => 'America/Grenada'],
            ['code' => 'GP', 'name' => 'Guadeloupe', 'phone_code' => '+590', 'timezone' => 'America/Guadeloupe'],
            ['code' => 'GU', 'name' => 'Guam', 'phone_code' => '+1-671', 'timezone' => 'Pacific/Guam'],
            ['code' => 'GT', 'name' => 'Guatemala', 'phone_code' => '+502', 'timezone' => 'America/Guatemala'],
            ['code' => 'GN', 'name' => 'Guinea', 'phone_code' => '+224', 'timezone' => 'Africa/Conakry'],
            ['code' => 'GW', 'name' => 'Guinea-Bissau', 'phone_code' => '+245', 'timezone' => 'Africa/Bissau'],
            ['code' => 'GY', 'name' => 'Guyana', 'phone_code' => '+592', 'timezone' => 'America/Guyana'],
            ['code' => 'HT', 'name' => 'Haiti', 'phone_code' => '+509', 'timezone' => 'America/Port-au-Prince'],
            ['code' => 'HM', 'name' => 'Heard Island & McDonald Islands', 'phone_code' => '+ — (no distinct)', 'timezone' => 'Indian/Kerguelen'],
            ['code' => 'VA', 'name' => 'Holy See (Vatican City State)', 'phone_code' => '+379', 'timezone' => 'Europe/Vatican'],
            ['code' => 'HN', 'name' => 'Honduras', 'phone_code' => '+504', 'timezone' => 'America/Tegucigalpa'],
            ['code' => 'HK', 'name' => 'Hong Kong', 'phone_code' => '+852', 'timezone' => 'Asia/Hong_Kong'],
            ['code' => 'HU', 'name' => 'Hungary', 'phone_code' => '+36', 'timezone' => 'Europe/Budapest'],
            ['code' => 'IS', 'name' => 'Iceland', 'phone_code' => '+354', 'timezone' => 'Atlantic/Reykjavik'],
            ['code' => 'IN', 'name' => 'India', 'phone_code' => '+91', 'timezone' => 'Asia/Kolkata'],
            ['code' => 'ID', 'name' => 'Indonesia', 'phone_code' => '+62', 'timezone' => 'Asia/Jakarta'],
            ['code' => 'IR', 'name' => 'Iran', 'phone_code' => '+98', 'timezone' => 'Asia/Tehran'],
            ['code' => 'IQ', 'name' => 'Iraq', 'phone_code' => '+964', 'timezone' => 'Asia/Baghdad'],
            ['code' => 'IE', 'name' => 'Ireland', 'phone_code' => '+353', 'timezone' => 'Europe/Dublin'],
            ['code' => 'IL', 'name' => 'Israel', 'phone_code' => '+972', 'timezone' => 'Asia/Jerusalem'],
            ['code' => 'IT', 'name' => 'Italy', 'phone_code' => '+39', 'timezone' => 'Europe/Rome'],
            ['code' => 'JM', 'name' => 'Jamaica', 'phone_code' => '+1-876', 'timezone' => 'America/Jamaica'],
            ['code' => 'JP', 'name' => 'Japan', 'phone_code' => '+81', 'timezone' => 'Asia/Tokyo'],
            ['code' => 'JO', 'name' => 'Jordan', 'phone_code' => '+962', 'timezone' => 'Asia/Amman'],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'phone_code' => '+7', 'timezone' => 'Asia/Almaty'],
            ['code' => 'KE', 'name' => 'Kenya', 'phone_code' => '+254', 'timezone' => 'Africa/Nairobi'],
            ['code' => 'KI', 'name' => 'Kiribati', 'phone_code' => '+686', 'timezone' => 'Pacific/Tarawa'],
            ['code' => 'KP', 'name' => 'Korea, North', 'phone_code' => '+850', 'timezone' => 'Asia/Pyongyang'],
            ['code' => 'KR', 'name' => 'Korea, South', 'phone_code' => '+82', 'timezone' => 'Asia/Seoul'],
            ['code' => 'KW', 'name' => 'Kuwait', 'phone_code' => '+965', 'timezone' => 'Asia/Kuwait'],
            ['code' => 'KG', 'name' => 'Kyrgyzstan', 'phone_code' => '+996', 'timezone' => 'Asia/Bishkek'],
            ['code' => 'LA', 'name' => 'Laos', 'phone_code' => '+856', 'timezone' => 'Asia/Vientiane'],
            ['code' => 'LV', 'name' => 'Latvia', 'phone_code' => '+371', 'timezone' => 'Europe/Riga'],
            ['code' => 'LB', 'name' => 'Lebanon', 'phone_code' => '+961', 'timezone' => 'Asia/Beirut'],
            ['code' => 'LS', 'name' => 'Lesotho', 'phone_code' => '+266', 'timezone' => 'Africa/Maseru'],
            ['code' => 'LR', 'name' => 'Liberia', 'phone_code' => '+231', 'timezone' => 'Africa/Monrovia'],
            ['code' => 'LY', 'name' => 'Libya', 'phone_code' => '+218', 'timezone' => 'Africa/Tripoli'],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'phone_code' => '+423', 'timezone' => 'Europe/Vaduz'],
            ['code' => 'LT', 'name' => 'Lithuania', 'phone_code' => '+370', 'timezone' => 'Europe/Vilnius'],
            ['code' => 'LU', 'name' => 'Luxembourg', 'phone_code' => '+352', 'timezone' => 'Europe/Luxembourg'],
            ['code' => 'MO', 'name' => 'Macau', 'phone_code' => '+853', 'timezone' => 'Asia/Macau'],
            ['code' => 'MK', 'name' => 'North Macedonia', 'phone_code' => '+389', 'timezone' => 'Europe/Skopje'],
            ['code' => 'MG', 'name' => 'Madagascar', 'phone_code' => '+261', 'timezone' => 'Indian/Antananarivo'],
            ['code' => 'MW', 'name' => 'Malawi', 'phone_code' => '+265', 'timezone' => 'Africa/Blantyre'],
            ['code' => 'MY', 'name' => 'Malaysia', 'phone_code' => '+60', 'timezone' => 'Asia/Kuala_Lumpur'],
            ['code' => 'MV', 'name' => 'Maldives', 'phone_code' => '+960', 'timezone' => 'Indian/Maldives'],
            ['code' => 'ML', 'name' => 'Mali', 'phone_code' => '+223', 'timezone' => 'Africa/Bamako'],
            ['code' => 'MT', 'name' => 'Malta', 'phone_code' => '+356', 'timezone' => 'Europe/Malta'],
            ['code' => 'MH', 'name' => 'Marshall Islands', 'phone_code' => '+692', 'timezone' => 'Pacific/Majuro'],
            ['code' => 'MQ', 'name' => 'Martinique', 'phone_code' => '+596', 'timezone' => 'America/Martinique'],
            ['code' => 'MR', 'name' => 'Mauritania', 'phone_code' => '+222', 'timezone' => 'Africa/Nouakchott'],
            ['code' => 'MU', 'name' => 'Mauritius', 'phone_code' => '+230', 'timezone' => 'Indian/Mauritius'],
            ['code' => 'YT', 'name' => 'Mayotte', 'phone_code' => '+262', 'timezone' => 'Indian/Mayotte'],
            ['code' => 'MX', 'name' => 'Mexico', 'phone_code' => '+52', 'timezone' => 'America/Mexico_City'],
            ['code' => 'FM', 'name' => 'Micronesia', 'phone_code' => '+691', 'timezone' => 'Pacific/Chuuk'],
            ['code' => 'MD', 'name' => 'Moldova', 'phone_code' => '+373', 'timezone' => 'Europe/Chisinau'],
            ['code' => 'MC', 'name' => 'Monaco', 'phone_code' => '+377', 'timezone' => 'Europe/Monaco'],
            ['code' => 'MN', 'name' => 'Mongolia', 'phone_code' => '+976', 'timezone' => 'Asia/Ulaanbaatar'],
            ['code' => 'ME', 'name' => 'Montenegro', 'phone_code' => '+382', 'timezone' => 'Europe/Podgorica'],
            ['code' => 'MS', 'name' => 'Montserrat', 'phone_code' => '+1-664', 'timezone' => 'America/Montserrat'],
            ['code' => 'MA', 'name' => 'Morocco', 'phone_code' => '+212', 'timezone' => 'Africa/Casablanca'],
            ['code' => 'MZ', 'name' => 'Mozambique', 'phone_code' => '+258', 'timezone' => 'Africa/Maputo'],
            ['code' => 'MM', 'name' => 'Myanmar', 'phone_code' => '+95', 'timezone' => 'Asia/Yangon'],
            ['code' => 'NA', 'name' => 'Namibia', 'phone_code' => '+264', 'timezone' => 'Africa/Windhoek'],
            ['code' => 'NR', 'name' => 'Nauru', 'phone_code' => '+674', 'timezone' => 'Pacific/Nauru'],
            ['code' => 'NP', 'name' => 'Nepal', 'phone_code' => '+977', 'timezone' => 'Asia/Kathmandu'],
            ['code' => 'NL', 'name' => 'Netherlands', 'phone_code' => '+31', 'timezone' => 'Europe/Amsterdam'],
            ['code' => 'NC', 'name' => 'New Caledonia', 'phone_code' => '+687', 'timezone' => 'Pacific/Noumea'],
            ['code' => 'NZ', 'name' => 'New Zealand', 'phone_code' => '+64', 'timezone' => 'Pacific/Auckland'],
            ['code' => 'NI', 'name' => 'Nicaragua', 'phone_code' => '+505', 'timezone' => 'America/Managua'],
            ['code' => 'NE', 'name' => 'Niger', 'phone_code' => '+227', 'timezone' => 'Africa/Niamey'],
            ['code' => 'NG', 'name' => 'Nigeria', 'phone_code' => '+234', 'timezone' => 'Africa/Lagos'],
            ['code' => 'NU', 'name' => 'Niue', 'phone_code' => '+683', 'timezone' => 'Pacific/Niue'],
            ['code' => 'NF', 'name' => 'Norfolk Island', 'phone_code' => '+672', 'timezone' => 'Pacific/Norfolk'],
            ['code' => 'MP', 'name' => 'Northern Mariana Islands', 'phone_code' => '+1-670', 'timezone' => 'Pacific/Saipan'],
            ['code' => 'NO', 'name' => 'Norway', 'phone_code' => '+47', 'timezone' => 'Europe/Oslo'],
            ['code' => 'OM', 'name' => 'Oman', 'phone_code' => '+968', 'timezone' => 'Asia/Muscat'],
            ['code' => 'PK', 'name' => 'Pakistan', 'phone_code' => '+92', 'timezone' => 'Asia/Karachi'],
            ['code' => 'PW', 'name' => 'Palau', 'phone_code' => '+680', 'timezone' => 'Pacific/Palau'],
            ['code' => 'PS', 'name' => 'Palestine', 'phone_code' => '+970', 'timezone' => 'Asia/Gaza'],
            ['code' => 'PA', 'name' => 'Panama', 'phone_code' => '+507', 'timezone' => 'America/Panama'],
            ['code' => 'PG', 'name' => 'Papua New Guinea', 'phone_code' => '+675', 'timezone' => 'Pacific/Port_Moresby'],
            ['code' => 'PY', 'name' => 'Paraguay', 'phone_code' => '+595', 'timezone' => 'America/Asuncion'],
            ['code' => 'PE', 'name' => 'Peru', 'phone_code' => '+51', 'timezone' => 'America/Lima'],
            ['code' => 'PH', 'name' => 'Philippines', 'phone_code' => '+63', 'timezone' => 'Asia/Manila'],
            ['code' => 'PL', 'name' => 'Poland', 'phone_code' => '+48', 'timezone' => 'Europe/Warsaw'],
            ['code' => 'PT', 'name' => 'Portugal', 'phone_code' => '+351', 'timezone' => 'Europe/Lisbon'],
            ['code' => 'PR', 'name' => 'Puerto Rico', 'phone_code' => '+1-787', 'timezone' => 'America/Puerto_Rico'],
            ['code' => 'QA', 'name' => 'Qatar', 'phone_code' => '+974', 'timezone' => 'Asia/Qatar'],
            ['code' => 'RE', 'name' => 'Réunion', 'phone_code' => '+262', 'timezone' => 'Indian/Reunion'],
            ['code' => 'RO', 'name' => 'Romania', 'phone_code' => '+40', 'timezone' => 'Europe/Bucharest'],
            ['code' => 'RU', 'name' => 'Russia', 'phone_code' => '+7', 'timezone' => 'Europe/Moscow'],
            ['code' => 'RW', 'name' => 'Rwanda', 'phone_code' => '+250', 'timezone' => 'Africa/Kigali'],
            ['code' => 'BL', 'name' => 'Saint Barthélemy', 'phone_code' => '+590', 'timezone' => 'America/St_Barthelemy'],
            ['code' => 'SH', 'name' => 'Saint Helena', 'phone_code' => '+290', 'timezone' => 'Atlantic/St_Helena'],
            ['code' => 'KN', 'name' => 'Saint Kitts & Nevis', 'phone_code' => '+1-869', 'timezone' => 'America/St_Kitts'],
            ['code' => 'LC', 'name' => 'Saint Lucia', 'phone_code' => '+1-758', 'timezone' => 'America/St_Lucia'],
            ['code' => 'MF', 'name' => 'Saint Martin (French part)', 'phone_code' => '+590', 'timezone' => 'America/Marigot'],
            ['code' => 'PM', 'name' => 'Saint Pierre & Miquelon', 'phone_code' => '+508', 'timezone' => 'America/Miquelon'],
            ['code' => 'VC', 'name' => 'Saint Vincent & the Grenadines', 'phone_code' => '+1-784', 'timezone' => 'America/St_Vincent'],
            ['code' => 'WS', 'name' => 'Samoa', 'phone_code' => '+685', 'timezone' => 'Pacific/Apia'],
            ['code' => 'SM', 'name' => 'San Marino', 'phone_code' => '+378', 'timezone' => 'Europe/San_Marino'],
            ['code' => 'ST', 'name' => 'Sao Tome & Principe', 'phone_code' => '+239', 'timezone' => 'Africa/Sao_Tome'],
            ['code' => 'SA', 'name' => 'Saudi Arabia', 'phone_code' => '+966', 'timezone' => 'Asia/Riyadh'],
            ['code' => 'SN', 'name' => 'Senegal', 'phone_code' => '+221', 'timezone' => 'Africa/Dakar'],
            ['code' => 'RS', 'name' => 'Serbia', 'phone_code' => '+381', 'timezone' => 'Europe/Belgrade'],
            ['code' => 'SC', 'name' => 'Seychelles', 'phone_code' => '+248', 'timezone' => 'Indian/Mahe'],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'phone_code' => '+232', 'timezone' => 'Africa/Freetown'],
            ['code' => 'SG', 'name' => 'Singapore', 'phone_code' => '+65', 'timezone' => 'Asia/Singapore'],
            ['code' => 'SK', 'name' => 'Slovakia', 'phone_code' => '+421', 'timezone' => 'Europe/Bratislava'],
            ['code' => 'SI', 'name' => 'Slovenia', 'phone_code' => '+386', 'timezone' => 'Europe/Ljubljana'],
            ['code' => 'SB', 'name' => 'Solomon Islands', 'phone_code' => '+677', 'timezone' => 'Pacific/Guadalcanal'],
            ['code' => 'SO', 'name' => 'Somalia', 'phone_code' => '+252', 'timezone' => 'Africa/Mogadishu'],
            ['code' => 'ZA', 'name' => 'South Africa', 'phone_code' => '+27', 'timezone' => 'Africa/Johannesburg'],
            ['code' => 'SS', 'name' => 'South Sudan', 'phone_code' => '+211', 'timezone' => 'Africa/Juba'],
            ['code' => 'ES', 'name' => 'Spain', 'phone_code' => '+34', 'timezone' => 'Europe/Madrid'],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'phone_code' => '+94', 'timezone' => 'Asia/Colombo'],
            ['code' => 'SD', 'name' => 'Sudan', 'phone_code' => '+249', 'timezone' => 'Africa/Khartoum'],
            ['code' => 'SR', 'name' => 'Suriname', 'phone_code' => '+597', 'timezone' => 'America/Paramaribo'],
            ['code' => 'SJ', 'name' => 'Svalbard & Jan Mayen', 'phone_code' => '+47', 'timezone' => 'Arctic/Longyearbyen'],
            ['code' => 'SE', 'name' => 'Sweden', 'phone_code' => '+46', 'timezone' => 'Europe/Stockholm'],
            ['code' => 'CH', 'name' => 'Switzerland', 'phone_code' => '+41', 'timezone' => 'Europe/Zurich'],
            ['code' => 'SY', 'name' => 'Syria', 'phone_code' => '+963', 'timezone' => 'Asia/Damascus'],
            ['code' => 'TW', 'name' => 'Taiwan', 'phone_code' => '+886', 'timezone' => 'Asia/Taipei'],
            ['code' => 'TJ', 'name' => 'Tajikistan', 'phone_code' => '+992', 'timezone' => 'Asia/Dushanbe'],
            ['code' => 'TZ', 'name' => 'Tanzania', 'phone_code' => '+255', 'timezone' => 'Africa/Dar_es_Salaam'],
            ['code' => 'TH', 'name' => 'Thailand', 'phone_code' => '+66', 'timezone' => 'Asia/Bangkok'],
            ['code' => 'TL', 'name' => 'Timor-Leste', 'phone_code' => '+670', 'timezone' => 'Asia/Dili'],
            ['code' => 'TG', 'name' => 'Togo', 'phone_code' => '+228', 'timezone' => 'Africa/Lome'],
            ['code' => 'TK', 'name' => 'Tokelau', 'phone_code' => '+690', 'timezone' => 'Pacific/Fakaofo'],
            ['code' => 'TO', 'name' => 'Tonga', 'phone_code' => '+676', 'timezone' => 'Pacific/Tongatapu'],
            ['code' => 'TT', 'name' => 'Trinidad & Tobago', 'phone_code' => '+1-868', 'timezone' => 'America/Port_of_Spain'],
            ['code' => 'TN', 'name' => 'Tunisia', 'phone_code' => '+216', 'timezone' => 'Africa/Tunis'],
            ['code' => 'TR', 'name' => 'Turkey', 'phone_code' => '+90', 'timezone' => 'Europe/Istanbul'],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'phone_code' => '+993', 'timezone' => 'Asia/Ashgabat'],
            ['code' => 'TC', 'name' => 'Turks & Caicos Islands', 'phone_code' => '+1-649', 'timezone' => 'America/Grand_Turk'],
            ['code' => 'TV', 'name' => 'Tuvalu', 'phone_code' => '+688', 'timezone' => 'Pacific/Funafuti'],
            ['code' => 'UG', 'name' => 'Uganda', 'phone_code' => '+256', 'timezone' => 'Africa/Kampala'],
            ['code' => 'UA', 'name' => 'Ukraine', 'phone_code' => '+380', 'timezone' => 'Europe/Kiev'],
            ['code' => 'AE', 'name' => 'United Arab Emirates', 'phone_code' => '+971', 'timezone' => 'Asia/Dubai'],
            ['code' => 'GB', 'name' => 'United Kingdom', 'phone_code' => '+44', 'timezone' => 'Europe/London'],
            ['code' => 'US', 'name' => 'United States', 'phone_code' => '+1', 'timezone' => 'America/New_York'],
            ['code' => 'UY', 'name' => 'Uruguay', 'phone_code' => '+598', 'timezone' => 'America/Montevideo'],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'phone_code' => '+998', 'timezone' => 'Asia/Tashkent'],
            ['code' => 'VU', 'name' => 'Vanuatu', 'phone_code' => '+678', 'timezone' => 'Pacific/Efate'],
            ['code' => 'VE', 'name' => 'Venezuela', 'phone_code' => '+58', 'timezone' => 'America/Caracas'],
            ['code' => 'VN', 'name' => 'Vietnam', 'phone_code' => '+84', 'timezone' => 'Asia/Ho_Chi_Minh'],
            ['code' => 'WF', 'name' => 'Wallis & Futuna', 'phone_code' => '+681', 'timezone' => 'Pacific/Wallis'],
            ['code' => 'EH', 'name' => 'Western Sahara', 'phone_code' => '+212', 'timezone' => 'Africa/El_Aaiun'],
            ['code' => 'YE', 'name' => 'Yemen', 'phone_code' => '+967', 'timezone' => 'Asia/Aden'],
            ['code' => 'ZM', 'name' => 'Zambia', 'phone_code' => '+260', 'timezone' => 'Africa/Lusaka'],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'phone_code' => '+263', 'timezone' => 'Africa/Harare'],
        ];

        DB::table('countries')->insert($countries);
    }
}
